### ISSUE TITLE
[Client][Design] InterviewTest 페이지 디자인 개선

### ISSUE THREAD

**Issue by findmytrueself** [codestates/road-to-interview#117]
## ISSUE
- Group: client
- Type: style
- Detail: 버튼 애니메이션과 같은 효과 추가

# TODO
- [x] 버튼 호버 효과
- [x] 버튼 디자인 수정
- [x] 데스크탑 반응형 타이머카운터 디자인
- [ ] 답변의 길이가 길때 페이지로 나누어서 왔다갔다 할 수 있게 구현하기 (Advance)
