### ISSUE TITLE
[Client][Mockup] 목업 데이터 준비하기

### ISSUE THREAD

**Issue by ppoyami** [codestates/road-to-interview#12]
## ISSUE
- Group: client
- Type: feature
- Detail: 정적 페이지 디자인을 위한 목업 데이터를 생성합니다.

# TODO

- [ ] 메인페이지에 사용할 인터뷰 목록 데이터
- [ ] 인터뷰 테스트에 필요한 질문 데이터
- [ ] 인터뷰 결과 페이지에 필요한 나의 답변 데이터
- [ ] 베스트 답변 페이지에 필요한 모범답안과 다른 유저의 답변 데이터
