### ISSUE TITLE
[Client] Recruit페이지 애니메이션

### ISSUE THREAD

**Issue by findmytrueself** [codestates/road-to-interview#152]
## ISSUE
- Group: client
- Type: feature
- Detail : 보이는 컬럼은 페이드아웃처리 , 새로운 컬럼은 페이드인으로 보이기

# TODO
- [ ] 최초의 화면 fade in
- [ ] 기존화면 fade out
- [ ] 새로운 화면 fade in
