### ISSUE TITLE
[Client] 마무리작업

### ISSUE THREAD

**Issue by findmytrueself** [codestates/road-to-interview#168]
## ISSUE
- Group: client or server
- Type: feature
- Detail: 사용하면서 버그 찾아야함 , 백엔드 데이터 추가해야함

# TODO
- [x] 테스트페이지 결과모달 버튼 디자인 , 애니메이션
- [x] 테스트페이지 결과모달 반응형 디자인
- [x] 전반적인 디테일 작업
- [x] 백엔드 데이터 추가
- [ ] 햄버거nav바 background 흐리게 하기 ,  
- [ ] 햄버거 nav바 스크롤 내리면 짤리는 css 수정
- [ ] 햄버거 바깥영역 누르면 nav바 모달 꺼지게 수정
- [ ] 헤더 nav바 고정시키기
- [x] 태블릿사이즈 헤더 nav바 폰트사이즈 수정
