### ISSUE TITLE
[Client][InterviewResult, BreakTime] 인터뷰 결과 페이지 디자인

### ISSUE THREAD

**Issue by ppoyami** [codestates/road-to-interview#30]
## ISSUE
- Group: client
- Type: feature
- Detail: 인터뷰 결과 페이지를 디자인합니다.

# TODO

- [x] BreakTime 페이지 디자인
- [ ] 나의 답변 페이지 디자인
- [ ] 베스트 답변 (모범답안 및 다른 사람의 답변) (모달 내부)
