### ISSUE TITLE
[Client][Create] Create 페이지 디자인 및 상태관리

### ISSUE THREAD

**Issue by ppoyami** [codestates/road-to-interview#49]
## ISSUE
- Group: client
- Type: feature
- Detail: Create 디자인 디자인 및 상태 관리 (유효성 체크 및 요청 데이터 구성하기)

# TODO

- [x] 카테고리를 입력할 수 있는 select 컴포넌트 작성
- [x] 상태관리 + 유효성 체크
- [x] 요청 데이터 구성
